name: mnist_pytorch_const
hyperparameters:
  learning_rate: 1.0
  n_filters1: 32
  n_filters2: 64
  dropout1: 0.25
  dropout2: 0.5
searcher:
  name: grid
  max_concurrent_trials: 2
  metric: validation_loss
  smaller_is_better: true
  max_length: 100
entrypoint: python3 train.py --epochs 1
